version: '3.8'

services:
  web:
    image: hvidigaljr/grupovalor:latest
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.valor.rule=Host(`valor.zobot.top`)
        - traefik.http.routers.valor.entrypoints=websecure
        - traefik.http.routers.valor.tls.certresolver=letsencryptresolver
        - traefik.http.services.valor.loadbalancer.server.port=3000
        - traefik.http.services.valor.loadbalancer.passHostHeader=true
        - traefik.http.routers.valor.service=valor
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

networks:
  portainer:
    external: true
    name: portainer