version: '3.8'

services:
  web:
    image: hvidigaljr/kaisan:latest
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.kaisan.rule=Host(`kaisan.zobot.top`)
        - traefik.http.routers.kaisan.entrypoints=websecure
        - traefik.http.routers.kaisan.tls.certresolver=letsencryptresolver
        - traefik.http.services.kaisan.loadbalancer.server.port=3000
        - traefik.http.services.kaisan.loadbalancer.passHostHeader=true
        - traefik.http.routers.kaisan.service=kaisan
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

networks:
  portainer:
    external: true
    name: portainer